---
- name: ensure virtualbox dependencies are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - dkms
 
- name: ensure oracle apt key is present for virtualbox
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present 

- name: ensure virtualbox repository is enabled
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
    update_cache: yes
    state: present

- name: ensure virtualbox-4.3 is installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - virtualbox-4.3
